SUPABASE_URL = "https://wkdbzoydxaaskewiuqwt.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndrZGJ6b3lkeGFhc2tld2l1cXd0Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1MDA1Njg2MywiZXhwIjoyMDY1NjMyODYzfQ.6aeYIYOsH_RxrveNEic4xqgcK2Vz7xOhPAUBtxFhme0"
